### ISSUE TITLE
ValueError: file is not a VPK (invalid magic)

### ISSUE THREAD

**Issue by kflittle01** [lasa01/io_import_vmf#148]
I just installed this addon to start porting TF2 maps to Unreal, but it keeps giving me this block of errors.

![image](https://user-images.githubusercontent.com/114956548/212266692-c72c2fd9-0429-45c7-a066-51ca582a5963.png)

Is there something I can do about this or is it a bug? I already have the Blender Source Tools addon as well.

**Comment by lasa01** [comment]
This usually means that you have a multipart .vpk file configured incorrectly. A multipart .vpk file consists of a main file ending with `_dir.vpk`, and the other parts end with `_001.vpk`, `_002.vpk` etc. You must not have any vpk files ending with numbers in the game configuration, as this will lead into the "File is not VPK" error. Instead, only having the `_dir.vpk` will provide access to all required files.

There is also a "Plumber" beta version in the releases page which has automatic game configuration. I recommend you try that in any case, since it is also a lot faster.

It could be also possible that if you have any wildcard directories configured, the wrong vpk files will get incorrectly detected with the older io_import_vmf. This is fixed in the Plumber beta.

**Comment by kflittle01** [comment]
Thanks a bunch, tried Plumber and it works!
