### ISSUE TITLE
No tool materials

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#49]
With the latest version, I dont happen to see any way to get materials for tools to import. They all come in wireframe, with no materials.

Obviously this is intended. But I just don't see an opt.

**Comment by lasa01** [comment]
The materials are actually imported, but since they are invisible ingame, the resulting material in Blender will be invisible too. They are also set to be displayed as wireframe in viewport to make them invisible in solid mode too. Different tools have different invisible materials assigned to them. You probably mean a way to import the Hammer preview textures for tools, not sure how useful that would be though.

**Comment by LethalDumpster** [comment]
I should perhaps have been more accurate with my wording. They don't import using material nodes, with their respective textures. They all lack their textures.
Older versions did used to bring in and use their textures, and I need that capability back.
